import random
import os
import sys
from bincovering.generators.base import Generate


class FileShuffleGenerator(Generate):
    def __init__(self, filename, path="./data/", num_swaps=0):
        """
        filename: name of the input file (e.g. 'OneOverN_20251027_232152.txt')
        path: directory containing the file
        num_swaps: number of random swaps to perform on the data
        """
        self._filename = filename
        self._path = path
        self._num_swaps = num_swaps
        self._numbers = []
        self._index = 0
        self._file_path = os.path.join(self._path, self._filename)

        if not os.path.exists(self._file_path):
            raise FileNotFoundError(f"File not found: {self._file_path}")

    def _load_file(self):
        """Read all numeric values from the input file into memory."""
        with open(self._file_path, "r") as f:
            # Parse floats from lines, ignoring blanks
            self._numbers = [
                float(line.strip()) for line in f if line.strip()
            ]

    def _random_swap(self):
        """Perform a specified number of random swaps on the list."""
        n = len(self._numbers)
        for _ in range(self._num_swaps):
            i, j = random.sample(range(n), 2)
            self._numbers[i], self._numbers[j] = self._numbers[j], self._numbers[i]

    def start(self):
        """Load file and prepare shuffled sequence."""
        self._load_file()
        if self._num_swaps > 0:
            self._random_swap()
        self._index = 0
        return (
            f"FileShuffleGenerator started with file '{self._filename}' "
            f"and {self._num_swaps} random swaps."
        )

    def next(self):
        """Return the next number in the (possibly shuffled) list."""
        if self._index < len(self._numbers):
            val = self._numbers[self._index]
            self._index += 1
            return val
        else:
            raise StopIteration("No more items to generate")

    def stop(self):
        """Stop reading and return how many items were served."""
        return f"Generator stopped. Total items served: {self._index}"


# Example usage
#if __name__ == "__main__":
#    # Suppose this file was generated by OneOverNGenerator earlier
#    filename = "OneOverN_20251027_232152.txt"
#    gen = FileShuffleGenerator(filename, path="./src/data/", num_swaps=100)
#    print(gen.start())
#
#    try:
#        while True:
#            print(gen.next())
#    except StopIteration:
#        pass
#
#    print(gen.stop())

