import random

import matplotlib.pyplot as plt


# Function to read numbers from a file
def read_numbers_from_file(filename):
    with open(filename, 'r') as file:
        numbers = [int(line.strip()) for line in file]
    return numbers


# Function to plot the numbers
def plot_numbers(numbers, title):
    plt.figure(figsize=(10, 5))
    plt.plot(numbers, marker='o', linestyle=' ', color='b')
    plt.title(title)
    plt.xlabel('Index')
    plt.ylabel('Number')
    plt.grid(True)
    plt.show()


def reorder_numbers(numbers, filename_core, sortOrShuffle):
    if sortOrShuffle == 1:
        numbers.sort()
        filename = "../sort_" + filename_core
    elif sortOrShuffle == 2:
        random.shuffle(numbers)
        random.shuffle(numbers)
        filename = "../rand_" + filename_core
    elif sortOrShuffle == 3:
        numbers.sort()
        numbers.reverse()
        filename = "../revSort_" + filename_core
    elif sortOrShuffle == 4:
        numbers.sort()
        mid = len(numbers) // 2
        first_half = numbers[:mid]
        second_half = numbers[mid:]
        second_half.reverse()
        numbers = first_half + second_half
        filename = "../middleBig_" + filename_core


    with open(filename, "w") as txt_file:
        for number in numbers:
            txt_file.write(str(number) + "\n")


# Main script
filename = 'opt_output.txt'  # The file generated by the C++ program
numbers = read_numbers_from_file(("../" + filename))
# sort
reorder_numbers(numbers, filename, 3)
# shuffle
#reorder_numbers(numbers, filename, 4)

#numbers.sort()
plot_numbers(numbers, 'Random Numbers from Optimal')
