import random
import sys


# Function to read numbers from a file
def read_numbers_from_file(filename):
    with open(filename, 'r') as file:
        numbers = [int(line.strip()) for line in file]
    return numbers


# Function to switch random numbers in array
def randomize_sort(numbers, amount):
    for i in range(0, amount):
        first_ind = random.randint(0, len(numbers)-1)
        second_ind = random.randint(0, len(numbers)-1)
        tmp = numbers[first_ind]
        numbers[first_ind] = numbers[second_ind]
        numbers[second_ind] = tmp
    return numbers


# Function for selecting how the items should be mixed
def reorder_numbers(numbers, filename, sortOrShuffle, percent_of_mix):
    if sortOrShuffle == 1:
        numbers.sort()
    elif sortOrShuffle == 2:
        random.shuffle(numbers)
        random.shuffle(numbers)
    elif sortOrShuffle == 3:
        numbers.sort()
        numbers.reverse()
    elif sortOrShuffle == 4:
        numbers.sort()
        mid = len(numbers) // 2
        first_half = numbers[:mid]
        second_half = numbers[mid:]
        second_half.reverse()
        numbers = first_half + second_half
    elif sortOrShuffle == 5:
        numbers.sort()
        numbers.reverse()
        numbers = randomize_sort(numbers, (int(len(numbers)*percent_of_mix)))

    # write mixed items to output file
    with open(filename, "w") as txt_file:
        for number in numbers:
            txt_file.write(str(number) + "\n")


# Main script
filename = sys.argv[1]                  # The file generated by the C++ program (generator.exe)
filename_output = sys.argv[2]           # output name of the file
filename_sorted = sys.argv[3]           # file with sorted items
percent_of_mix = int(sys.argv[4])       # what percent of items should be switched

numbers = read_numbers_from_file(filename)
# create file with sorted items for report
reorder_numbers(numbers, filename_sorted, 3, percent_of_mix)
# shuffle items (to see performance of algorithm)
print(int(len(numbers)*(percent_of_mix*0.01)))
reorder_numbers(numbers, filename_output, 5, percent_of_mix)

